#!/bin/bash

# Make sure only root can run our script
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

for dir in $*; do
	touch $dir/.profiles $dir/.slowpages $dir/.apache_stats
	touch $dir/.tag $dir/.release 
done
